-- TABLE 생성(유저, 글, 댓글, 북마크, 코드)

-- 사용자 정뵤 CPUSER
CREATE TABLE CPUSER
(
	OID VARCHAR2(11)		NOT NULL,
	ACCOUNT VARCHAR2(11)	NOT NULL,
	PASSWORD VARCHAR2(64),
	NAME VARCHAR2(64),
	NICKNAME VARCHAR2(64),
	GRADE VARCHAR2(64),
	GENDER VARCHAR2(11),
	EMAIL VARCHAR2(320),
	BIRTHDATE VARCHAR2(8),
	TELEPHONE VARCHAR2(50),
	LASTLOGINIP VARCHAR2(15),
	LASTLOGINAT DATE,
	CREATEDAT DATE,
	LASTMODIFIEDAT DATE,
	PLATFORM_TYPE VARCHAR2(384),
	ACCESS_TOKEN VARCHAR2(384)
)
TABLESPACE TBSCODEPLACE;

ALTER TABLE CPUSER ADD
(
	CONSTRAINT CUSER_PK PRIMARY KEY(OID)
	USING INDEX TABLESPACE TBSCODEPLACEINDEX
);

-- 질문 정보 CPDOCUMENT

CREATE TABLE CPDOCUMENT
(
	OID	VARCHAR2(11)			NOT NULL,
	PARENTSOID VARCHAR2(11)		NOT NULL,
	TITLE VARCHAR2(720)			NOT NULL,
	CREATOROID VARCHAR2(11),
	CREATEDAT DATE,
	LASTMODIFIEDAT DATE,
	CONTENTS VARCHAR2(3000),
	DOCTYPE VARCHAR2(1) DEFAULT 'N' NOT NULL,	-- 기본 글이면 N 답글이면 D
	VIEWCNT NUMBER DEFAULT 0,
	LIKECNT NUMBER DEFAULT 0,
	CMTCNT NUMBER DEFAULT 0,
	REPORTCNT NUMBER DEFAULT 0
)
TABLESPACE TBSCODEPLACE;

ALTER TABLE CPDOCUMENT ADD
(
	CONSTRAINT CPDOCUMENT_PK PRIMARY KEY (OID)
	USING INDEX TABLESPACE TBSCODEPLACEINDEX
);

CREATE INDEX CPDOC_CREATEAT ON CPDOCUMENT
(
	CREATEDAT ASC,
	OID ASC
)
TABLESPACE TBSCODEPLACEINDEX;

CREATE INDEX CPDOC_CREATOR ON CPDOCUMENT
(
	CREATOROID ASC,
	OID ASC
)
TABLESPACE TBSCODEPLACEINDEX;




-- 댓글 정보 CPCOMMENT

CREATE TABLE CPCOMMENT
(
	OID	VARCHAR2(11)			NOT NULL,
	TARGETOID VARCHAR2(11)		NOT NULL,
	CREATOROID VARCHAR2(11),
	CONTENTS VARCHAR2(2000),
	CREATEDAT DATE,
	MODIFIEDAT DATE,
	DELETESTATUS VARCHAR2(1) DEFAULT 'N' NOT NULL,
	REPORTCNT NUMBER DEFAULT 0
)
TABLESPACE TBSCODEPLACE;

ALTER TABLE CPCOMMENT ADD
(
	CONSTRAINT CPCOMMENT_PK PRIMARY KEY (OID)
	USING INDEX TABLESPACE TBSCODEPLACEINDEX
);

CREATE INDEX CPCMT_CREATEDAT ON CPCOMMENT
(
	CREATEDAT DESC,
	OID ASC
)
TABLESPACE TBSCODEPLACEINDEX;




-- 북마크

CREATE TABLE CPBOOKMARK
(
	OID VARCHAR2(11)		NOT NULL,
	TARGETOID VARCHAR2(11)  NOT NULL,
	DOCOID VARCHAR2(11)		NOT NULL,
	ADDAT DATE
)
TABLESPACE TBSCODEPLACE;

ALTER TABLE CPBOOKMARK ADD
(
	CONSTRAINT CPBOOKMARK_PK PRIMARY KEY (OID)
	USING INDEX TABLESPACE TBSCODEPLACEINDEX
);

CREATE INDEX CPBM_ADDAT ON CPBOOKMARK
(
	ADDAT ASC,
	OID ASC
)
TABLESPACE TBSCODEPLACEINDEX;



-- 컴파일러

CREATE TABLE CPCOMPILE
(
	OID VARCHAR2(11)			NOT NULL,
	CREATOROID VARCHAR2(11),
	COMPILEDAT DATE,
	INPUT VARCHAR2(3000),
	OUTPUT VARCHAR2(3000),
	STATUS VARCHAR2(1) DEFAULT 'S'    --컴파일 성공시 S, 실패시 D
)
TABLESPACE TBSCODEPLACE;

ALTER TABLE CPCOMPILE ADD
(
	CONSTRAINT CPCOMPILE_PK PRIMARY KEY (OID)
	USING INDEX TABLESPACE TBSCODEPLACEINDEX
);

CREATE INDEX CPCOMPLIE_COMPILEDAT ON CPCOMPILE
(
	COMPILEDAT ASC,
	OID ASC
)
TABLESPACE TBSCODEPLACEINDEX;