-- 테이블 TABLESPACE
CREATE TABLESPACE TBSCODEPLACE
DATAFILE 'D:\data\cp\tbscodeplace.dbf' size 100M
AUTOEXTEND ON NEXT 50M MAXSIZE 1000M ONLINE;

-- 인덱스 TABLESPACE
CREATE TABLESPACE TBSCODEPLACEINDEX
DATAFILE 'D:\data\cp\tbsCodePlaceIndex.dbf' size 100M
AUTOEXTEND ON NEXT 50M MAXSIZE 1000M ONLINE;

-- TMP TABLESPACE
CREATE TEMPORARY TABLESPACE TBSCODEPLACETEMP
TEMPFILE 'D:\data\cp\tbsCodePlaceTemp.dbf' size 10M
AUTOEXTEND ON NEXT 10M MAXSIZE 200M;